AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Description: Path to the configuration file
  Region:
    Type: String
    Description: Region in which we are setting up


Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub 
        - 'kinesis-${env}-${region}'
        - env: !Ref Environment
          region: !Ref Region
      ShardCount: 1


Outputs:
  KinesisStreamName:
    Value: !Ref KinesisStream
    Description: Name of the Kinesis stream

  KinesisStreamArn:
    Value: !GetAtt KinesisStream.Arn
    Description: ARN of the Kinesis stream
