AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ConfigFile:
    Type: String

Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Sub 'kinesis-${ConfigFile.EnvironmentType}-${Region}'
      ShardCount: 1


Outputs:
  KinesisStreamName:
    Value: !Ref KinesisStream
    Description: Name of the Kinesis stream

  KinesisStreamArn:
    Value: !GetAtt KinesisStream.Arn
    Description: ARN of the Kinesis stream
