AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function to validate Kinesis data stream records

Resources:
  ValidationLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 128
      Timeout: 30
      ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/validation-lambda-repo:latest
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: arn:aws:kinesis:<region>:<account-id>:stream/<your-stream-name>
            StartingPosition: LATEST

  ValidationLambdaRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: validation-lambda-repo
