AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function to validate Kinesis data stream records

Parameters:
  ConfigFile:
    Type: String
    Description: Path to the configuration file

  KinesisStream:
    Type: String
    Description: ARN of the Kinesis stream

Resources:
  ValidationLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 128
      Timeout: 30
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Ref KinesisStream
            StartingPosition: LATEST

  ValidationLambdaRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: validation-lambda-repo
