AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function to validate Kinesis data stream records

Parameters:
  ConfigFile:
    Type: String
    Description: Path to the configuration file

  KinesisStream:
    Type: String
    Description: ARN of the Kinesis stream

Resources:
  ValidationLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'validation-lambda-${ConfigFile.EnvironmentType}-${Region}'
      PackageType: Image
      Timeout: 30
      CodeUri: ./src/validation-lambda/
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Ref KinesisStream
            StartingPosition: TRIM_HORIZON
            BatchSize: 1
    Metadata:
      Dockerfile: Dockerfile
      DcokerContext: ./src/validation-lambda/
      DockerTag: !Sub 'validation-lambda-${ConfigFile.EnvironmentType}-${Region}'


  ValidationLambdaRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: validation-lambda-repo
