AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function to filter Kinesis data stream records

Parameters:
  Environment:
    Type: String
    Description: Path to the configuration file
  Region:
    Type: String
    Description: Region in which we are setting up
  KinesisStream:
    Type: String
    Description: ARN of the Kinesis stream

Transform: AWS::Serverless-2016-10-31
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "validation-lambda-repo"
      ImageScanningConfiguration:
        ScanOnPush: true
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src/validation-lambda/
      DockerTag: !Sub 
        - 'validation-lambda-${env}-${region}'
        - env: !Ref Environment
          region: !Ref Region
  ValidationLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 
        - 'validation-lambda-${env}-${region}'
        - env: !Ref Environment
          region: !Ref Region
      PackageType: Image
      ImageUri: !GetAtt ECRRepository.RepositoryUri
      Architectures:
        - x86_64
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Ref KinesisStream
            StartingPosition: TRIM_HORIZON
            BatchSize: 100

Outputs:
  # ValidationLambdaECR:
  #   Value: !GetAtt ECRRepository.RepositoryUri
  ValidationLambdaArn:
    Value: !GetAtt ValidationLambdaFunction.Arn
