AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ConfigFile:
    Type: String

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'raw-transactions-${ConfigFile.EnvironmentType}-${Region}'

Outputs:
  S3BucketArn:
    Value: !GetAtt S3Bucket.Arn
    Description: ARN of the S3 bucket