name: test and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: uv python install
      - name: Run tests
        run: uv run pytest tests

  build-validation-lambda-ecr: 
    needs: test
    uses: heaven00/fraud-detection-aws/.github/workflows/build_and_deploy_images.yml@main
    with:
        aws-region: ca-central-1
        ecr-repo-name: fraud-detection/validation-lambda
        image-tag: ${{ github.sha }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-serverless-infra:
    # needs: build-validation-lambda-ecr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name fraud-detection-serverless \
            --template-file cloudformation/template.yml \
            --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM \
            --parameter-overrides Environment=dev Region=ca-central-1
